package com.example.demo.mapper;

import com.example.demo.mapper.model.TxLog;
import com.example.demo.mapper.model.TxLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TxLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    long countByExample(TxLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    int deleteByExample(TxLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    int insert(TxLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    int insertSelective(TxLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    List<TxLog> selectByExample(TxLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    TxLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TxLog record, @Param("example") TxLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TxLog record, @Param("example") TxLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TxLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tx_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TxLog record);
}